[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:api]
command=node /app/dist/api/server.js
directory=/app
user=nodejs
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/api.err.log
stdout_logfile=/var/log/supervisor/api.out.log
environment=HOME="/app",USER="nodejs"

[program:consumer]
command=node /app/dist/consumer/index.js
directory=/app
user=nodejs
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/consumer.err.log
stdout_logfile=/var/log/supervisor/consumer.out.log
environment=HOME="/app",USER="nodejs"

[program:nginx]
command=nginx -g "daemon off;"
user=root
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/nginx.err.log
stdout_logfile=/var/log/supervisor/nginx.out.log
