[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:api]
command=node /app/dist/api/server.js
directory=/app
user=nodejs
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/api.err.log
stdout_logfile=/var/log/supervisor/api.out.log
environment=HOME="/app",USER="nodejs",RABBITMQ_URL="%(ENV_RABBITMQ_URL)s",RABBITMQ_QUEUE="%(ENV_RABBITMQ_QUEUE)s",RABBITMQ_DLQ="%(ENV_RABBITMQ_DLQ)s",SALESFORCE_INSTANCE_URL="%(ENV_SALESFORCE_INSTANCE_URL)s",SALESFORCE_CLIENT_ID="%(ENV_SALESFORCE_CLIENT_ID)s",SALESFORCE_CLIENT_SECRET="%(ENV_SALESFORCE_CLIENT_SECRET)s",SALESFORCE_REFRESH_TOKEN="%(ENV_SALESFORCE_REFRESH_TOKEN)s",SALESFORCE_API_VERSION="%(ENV_SALESFORCE_API_VERSION)s",SALESFORCE_USERNAME="%(ENV_SALESFORCE_USERNAME)s",SALESFORCE_PASSWORD="%(ENV_SALESFORCE_PASSWORD)s",SALESFORCE_SECURITY_TOKEN="%(ENV_SALESFORCE_SECURITY_TOKEN)s",API_PORT="%(ENV_API_PORT)s",LOG_LEVEL="%(ENV_LOG_LEVEL)s",LOG_DIR="%(ENV_LOG_DIR)s"

[program:consumer]
command=node /app/dist/consumer/index.js
directory=/app
user=nodejs
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/consumer.err.log
stdout_logfile=/var/log/supervisor/consumer.out.log
environment=HOME="/app",USER="nodejs",RABBITMQ_URL="%(ENV_RABBITMQ_URL)s",RABBITMQ_QUEUE="%(ENV_RABBITMQ_QUEUE)s",RABBITMQ_DLQ="%(ENV_RABBITMQ_DLQ)s",SALESFORCE_INSTANCE_URL="%(ENV_SALESFORCE_INSTANCE_URL)s",SALESFORCE_CLIENT_ID="%(ENV_SALESFORCE_CLIENT_ID)s",SALESFORCE_CLIENT_SECRET="%(ENV_SALESFORCE_CLIENT_SECRET)s",SALESFORCE_REFRESH_TOKEN="%(ENV_SALESFORCE_REFRESH_TOKEN)s",SALESFORCE_API_VERSION="%(ENV_SALESFORCE_API_VERSION)s",SALESFORCE_USERNAME="%(ENV_SALESFORCE_USERNAME)s",SALESFORCE_PASSWORD="%(ENV_SALESFORCE_PASSWORD)s",SALESFORCE_SECURITY_TOKEN="%(ENV_SALESFORCE_SECURITY_TOKEN)s",API_PORT="%(ENV_API_PORT)s",LOG_LEVEL="%(ENV_LOG_LEVEL)s",LOG_DIR="%(ENV_LOG_DIR)s"

[program:nginx]
command=nginx -g "daemon off;"
user=root
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/nginx.err.log
stdout_logfile=/var/log/supervisor/nginx.out.log
